### ISSUE TITLE
Rationale for diverging from bs-webapi

### ISSUE THREAD

**Issue by glennsl** [derui/bs-dom-wrapper#2]
Hey. Just curious about what the rationale for this project is. Apart from being organized a bit differently I don't see any significant differences and it seems to be largely copied from bs-webapi (not that I mind, but I ask that you respect the license if you do)

**Comment by derui** [comment]
@glennsl 
Yes, you are right. Beginning of this project is for personal use for me. I had found (bs-webapi-incubator)[https://github.com/reasonml-community/bs-webapi-incubator] when I had wanted to write OCaml with bucklescript,  but (bs-webapi-incubator)[https://github.com/reasonml-community/bs-webapi-incubator] was created for reasonml..., so I had wrote porting for OCaml of (bs-webapi-incubator)[https://github.com/reasonml-community/bs-webapi-incubator].

But  it is not reason to not add license to source. I added licenses this project and sources in PR #3 , could you confirm it?

Last, thank you your contribution and read my poor english !

**Comment by glennsl** [comment]
License and attribution looks good. Thanks!

`bs-webapi` isn't Reason-specific though, you can use it with OCaml. BuckleScript actually bundles Reason and will compile Reason dependencies for you seamlessly. There's no noticeable difference at all, unless you go and read the source code.

I'd be happy to help you out if you've run across any issues with it, or need some additions or changes to it. I hang around the Reason [Discord](https://discord.gg/reasonml), where you'll also find the author of BuckleScript as well as lots of people that prefer OCaml over Reason. You're more than welcome to come by!

**Comment by derui** [comment]
> bs-webapi isn't Reason-specific though, you can use it with OCaml.

Really? I didn't know it. I'll try bs-webapi with my source, then switch to use it if I can convert current source.

Thanks a lot!
